---
- name: Build and deploy AWX
  hosts: awx
  roles:
    - {role: check_vars}
    - {role: image_build, when: "dockerhub_base is not defined"}
    - {role: image_push, when: "docker_registry is defined and dockerhub_base is not defined"}
    - {role: local_docker, when: "openshift_host is not defined and kubernetes_context is not defined"}
